### ISSUE TITLE
第一步就报错了

### ISSUE THREAD

**Issue by Niteip** [binaryai/bindiffmatch#1]
执行 pip install .[lowmem]  时报错：

![impicture_20240617_164849](https://github.com/binaryai/bindiffmatch/assets/5361655/9fa1316c-d3e8-42ab-8516-7d9f00a5b7cf)

卡在这里了

**Comment by hzqmwne** [comment]
git clone 下来应该不会报错，download zip 复现了图上的错误

修了一下 https://github.com/binaryai/bindiffmatch/commit/68af1791392b19fd784200444ddca4563cef0d0a ，现在 download zip 应该不会报错了

**Comment by Niteip** [comment]
> git clone 下来应该不会报错，download zip 复现了图上的错误
> 
> 修了一下 [68af179](https://github.com/binaryai/bindiffmatch/commit/68af1791392b19fd784200444ddca4563cef0d0a) ，现在 download zip 应该不会报错了

原来如此， 我下的是 release v1.0

重新下来 master 分之， 然后又解决了一些报错，能跑了。
